version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dadosaberto-img
    container_name: dadosabertos
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: dadosabertos-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
